{
 "title": "ClientSideMetrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number Of Active Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(gatling_scalaclass_allRequests_all_count{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Response Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(gatling_scalaclass_allRequests_all_min{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gatling_scalaclass_allRequests_all_mean{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gatling_scalaclass_allRequests_all_max{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Response Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(gatling_scalaclass_allRequests_all_mean{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(gatling_scalaclass_allRequests_all_percentiles95{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "75th Percentile Response Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(gatling_scalaclass_allRequests_all_percentiles75{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(gatling_scalaclass_allRequests_all_count{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PassCount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(gatling_scalaclass_allRequests_ok_count{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FailureCount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(gatling_scalaclass_allRequests_ko_count{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}